config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists
  resources :lists do
    resources :tasks,  only: [:index, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_parameter)
    if @list.save
      redirect_to lists_path
    else
      redirect_to root_path
    end
  end

  def show
    @list = List.find(params[:id])
    @task = Task.new
    @tasks = @list.tasks
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_parameter)
      redirect_to list_path
    else
      render 'edit'
    end
  end

  private

  def list_parameter
    params.require(:list).permit(:name)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.new(task_parameter)
    if @task.save
      redirect_to "/lists/#{@task.list.id}"
    else
      redirect_to "/lists/#{@task.list.id}"
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
    if @task.destroy
      redirect_to "/lists/#{@task.list.id}"
    else
      redirect_to "/lists/#{@task.list.id}"
    end
  end

  private

  def task_parameter
    params.require(:task).permit(:title, :content, :start_time)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<%= render "shared/header" %>

<div class="list">
  <p class="new-list">リスト名を変更</p>
  <%= form_with(model: @list, local: true) do |form| %>
    <div class="name">
      リスト名を入力してください
      <%= form.text_field :name, class:"form-tag-box1"%>
    </div>
    <div class="submit">
      <%= form.submit class:"submit-box"%>
    </div>
    <%= link_to '戻る', list_path, class: "back-btn2" %>
  <% end %>
</div>

app/views/lists/index.html.erb
<%= render "shared/header" %>

<div class="list">
  <p class="new-list">新しいリストを作成</p>
  <%= form_with(model: @list, local: true) do |form| %>
    <div class="name">
      リスト名を入力してください
      <%= form.text_field :name, class:"form-tag-box1"%>
    </div>
    <div class="submit">
      <%= form.submit class:"submit-box"%>
    </div>
  <% end %>
</div>

<ul>
<div class="list-show">
  <% @lists.each do |list| %>
    <div class="index-name"><li><%= link_to list.name , list %></div></li>
  <% end %>
</div>
<ul>

app/views/lists/show.html.erb
<%= render "shared/header" %>

<div class="list-content">
  <h1 class="list-name">リスト名 『<%= @list.name %>』</h1>
  <%= link_to '削除',list_path(@list.id), class: "destroy-btn", method: :delete, data: { confirm: '本当に?' } %>
  <%= link_to '編集', edit_list_path(@list), class: "edit-btn" %>
  <%= link_to '戻る', root_path, class: "back-btn" %>
</div>

<h2 class="task-get">タスクを追加</h2>
<div class="task-new">

  <%= form_with(model: [@list, @task], local: true) do |form| %>

    <div class="title">
      <div class="form-tag">タイトル  <span class="title-hissu">(必須)</span></div>
      <%= form.text_field :title,  class:"form-tag-box"%>
    </div>




    <div class="time">
      <div class="form-tag form-tag-time">時間</div>
      <%= form.datetime_field :start_time, class: 'form-control' %>
    </div>

    <div class="submit">
      <%= form.submit class:"submit-box"%>
    </div>


  <% end %>
</div>

<ul>
<div class="task-list">
  <% @tasks.each do |task| %>
    <div class="list-border">
      <li><%= task.title%>
      <%= task.start_time&.strftime("%Y年%m月%d日%H時%M分") %>
      <%= link_to '完了',list_task_path(@list, task), class: "destroy-btn2", method: :delete %>
      </li>
    </div>
  <% end %>
</ul>

app/views/shared/_header.html.erb
<header>
  <div class="header-left">
    <%= link_to 'ToDo LIST', root_path, class:"todolist" %>
  </div>
</header>